apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc-multiapp
  labels:
    type: frontend
spec:
  replicas: 3
  selector:
    app: my-rc-multiapp
  template:
    metadata:
      name: my-rc-multiapp
      labels:
        app: my-rc-multiapp
    spec:
      containers:
      - name: nginxtest
        image: nginx
        ports:
        - name: nginxport
          containerPort: 80
      - name: jenkinstest
        image: jenkins/jenkins:lts
        ports:
        - name: jenkinport
          containerPort: 8080
        - name: slaveagent
          containerPort: 50000