apiVersion: v1
kind: Pod
metadata:
  name: my-app-multi
  labels:
    type: frontend
spec:
  containers:
  - name: nginxtest
    image: nginx
    ports:
      - name: nginxport
        containerPort: 80
  - name: jenkinstest
    image: jenkins/jenkins:lts
    ports:
    - name: jenkinport
      containerPort: 8080
    - name: slaveagent
      containerPort: 50000